---
# Example playbook to install yq and jq

- name: Install yq and jq
  hosts: all
  become: yes
  tasks:
  - name: Install dependencies
    package:
      name: libyaml-dev
      state: present

  - name: Install yq
    shell: |
      set -ex
      curl https://github.com/mikefarah/yq/releases/download/3.4.0/yq_linux_amd64 -o /usr/local/bin/yq
      chmod +x /usr/local/bin/yq

  - name: Install jq
    when: "'apt' in ansible_pkg_mgr"
    apt:
      name: jq
      state: present

  - name: Install jq
    when: "'yum' in ansible_pkg_mgr"
    yum:
      name: jq
      state: present

  - name: Install jq
    when: "'dnf' in ansible_pkg_mgr"
    dnf:
      name: jq
      state: present

  - name: Install jq
    when: "'zypper' in ansible_pkg_mgr"
    zypper:
      name: jq
      state: present

  - name: Install jq
    when: "'pacman' in ansible_pkg_mgr"
    pacman:
      name: jq
      state: present

  - name: Install jq
    when: "'emerge' in ansible_pkg_mgr"
    emerge:
      name: jq
      state: present

  - name: Verify yq installation
    shell: yq --version
    register: yq_version
  - name: Show yq version
    debug:
      var: yq_version.stdout_lines

  - name: Verify jq installation
    shell: jq --version
    register: jq_version
  - name: Show jq version
    debug:
      var: jq_version.stdout_lines
