- name: Clone Git Repositories
  hosts: all
  become: true
  tasks:
    - name: Purge https://github.com/dragoscirjan/myhome-monitor
      shell: |
        rm -rf /opt/myhome-monitor

    - name: Clone https://github.com/dragoscirjan/myhome-monitor
      git:
        repo: https://github.com/dragoscirjan/myhome-monitor
        dest: /opt/myhome-monitor
        version: main
        track_submodules: true
        clone: yes

    - name: Install apt dependencies
      apt:
        name:
          - python3
          - python3-pip
          - bluez
          - libbluetooth-dev
          - build-essential
          - libglib2.0-dev
        state: present

    - name: Install python dependencies
      pip:
        name:
          - bluepy
          - requests
          - paho-mqtt
        state: present
