---
- name: Change hostname based on inventory variables
  hosts: all
  become: true
  vars:
    west_hostname: "ubuntu-pi4"
    east_hostname: "ubuntu-pi2"
  tasks:
    - name: Set hostname for west
      when: "'west' in inventory_hostname"
      hostname:
        name: "{{ west_hostname }}"

    - name: Set hostname for east
      when: "'east' in inventory_hostname"
      hostname:
        name: "{{ east_hostname }}"
