- name: Add SSH key to authorized_keys
  hosts: all
  become: true
  become_user: root
  vars:
    clean_authorized_keys: false
  tasks:
    - name: Remove all authorized keys
      shell: |
        set -ex
        echo "" > ~/.ssh/authorized_keys
      when: clean_authorized_keys
    - name: Copy SSH key to authorized_keys
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '../.ssh/id_ed25519.pub') }}"
