---
- name: Install make, build-essential, netstat, git, jq, yq
  hosts: all
  become: true
  vars:
    yq_version: 4.31.2
  tasks:
    # - name: Install dependencies
    #   package:
    #     name: build-essential
    #     state: present
    #   when: "'Debian' in ansible_os_family or 'Ubuntu' in ansible_os_family"

    # - name: Install dependencies
    #   package:
    #     name: "gcc, make"
    #     state: present
    #   when: "'RedHat' in ansible_os_family or 'Fedora' in ansible_os_family"

    # - name: Install dependencies
    #   package:
    #     name: "gcc, make, net-tools"
    #     state: present
    #   when: "'Manjaro' in ansible_os_family"

    # - name: Install dependencies
    #   package:
    #     name: "gcc, make, net-tools"
    #     state: present
    #   when: "'Gentoo' in ansible_os_family"

    # - name: Install git
    #   package:
    #     name: git
    #     state: present

    # - name: Install jq
    #   package:
    #     name: jq
    #     state: present

    - name: Copy yq installer
      copy:
        src: ../install/yq.sh
        dest: /tmp/yq.sh
        mode: "u+rwx,g+rx,o+rx"   # set the permissions for the file

    - name: Execute bash file on remote machine
      shell: /tmp/yq.sh
      register: yq_install

    - name: Show yq install
      debug:
        var: yq_install.stdout_lines

    - name: Verify jq installation
      shell: jq --version
      register: jq_version
    - name: Show jq version
      debug:
        var: jq_version.stdout_lines
