---
- name: Install make, build-essential, netstat, git, jq, yq
  hosts: all
  become: true
  vars:
    yq_version: 4.32.1
  tasks:
    - name: Install dependencies
      package:
        name: build-essential
        state: present
      when: "'Debian' in ansible_os_family or 'Ubuntu' in ansible_os_family"

    - name: Install dependencies
      package:
        name: "gcc, make"
        state: present
      when: "'RedHat' in ansible_os_family or 'Fedora' in ansible_os_family"

    - name: Install dependencies
      package:
        name: "gcc, make, net-tools"
        state: present
      when: "'Manjaro' in ansible_os_family"

    - name: Install dependencies
      package:
        name: "gcc, make, net-tools"
        state: present
      when: "'Gentoo' in ansible_os_family"

    - name: Install git
      package:
        name: git
        state: present

    - name: Install jq
      package:
        name: jq
        state: present

    - name: Copy yq installer
      copy:
        dest: /tmp/yq.sh
        content: |
          #! /bin/bash
          set -ex

          arch=$(dpkg --print-architecture)
          if [[ $arch == *"arm64"* || $arch == *"aarch64"* ]]; then
            echo "installing arm64"
            curl -L -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v$1/yq_linux_arm64
          fi
          if [[ $arch == *"armv"* || $arch == *"armh"* ]]; then
            echo "installing arm"
            curl -L -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v$1/yq_linux_arm
          fi
          if [[ $arch == *"amd64"* ]]; then
            echo "installing amd64"
            curl -L -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v$1/yq_linux_amd64
          fi
          chmod +x /usr/local/bin/yq

          yq --version

        mode: "u+rwx,g+rx,o+rx"   # set the permissions for the file
        # relative: yes

    - name: Execute bash file on remote machine
      script: "/tmp/yq.sh {{yq_version}}"
      register: yq_install

    - name: Show yq install
      debug:
        var: yq_install.stdout_lines
